# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

export XDG_CURRENT_DESKTOP=sway # xdg-desktop-portal
export XDG_SESSION_DESKTOP=sway # systemd
export XDG_SESSION_TYPE=wayland


export PATH="$HOME/.cargo/bin:$PATH"
#export PATH="$HOME/.config/emacs/bin"
export TERMINAL="kitty"
export EDITOR="nvim"

export PATH="/home/rodhfr/AppImages/audiorelay-0.27.5/bin:$PATH"

bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'

. "$HOME/.cargo/env"
alias hide="swayhide"
alias delay="--audio-delay=-1.2"

cl() { cd "$@" && ls; }

pwd
ls

export SCRCPYCMD=$(cat ~/.config/scrcpy/scrcpy.conf)
export SCRCPYA20=$(cat ~/.config/scrcpy/scrcpya20.conf)
export SCRCPYA35=$(cat ~/.config/scrcpy/scrcpya35.conf)

strdiff() {
    if [ $# -ne 2 ]; then
        echo "Uso: strdiff \"string1\" \"string2\""
        return 1
    fi

    tmp1=$(mktemp /tmp/str1.XXXX)
    tmp2=$(mktemp /tmp/str2.XXXX)

    echo "$1" > "$tmp1"
    echo "$2" > "$tmp2"

    nvim -d "$tmp1" "$tmp2"

    rm -f "$tmp1" "$tmp2"
}


eval "$(starship init bash)"


. "$HOME/.atuin/bin/env"

[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
eval "$(atuin init bash)"
