[window]
opacity = 0.7

[colors.primary]
background = "#000000"


[font]
size = 14

[font.normal]
#family = "CaskaydiaCove Nerd Font Mono"
family = "Noto Sans Mono"

[keyboard]
bindings = [
  { key = "W", mods = "Control", chars = "| wl-copy\n" },
  { key = "N", mods = "Control", chars = "nautilus . > /dev/null 2>&1 &; disown && exit\n" },
  { key = "N", mods = "Control|Shift", chars = "nautilus . > /dev/null 2>&1 &; disown & swaymsg workspace 7 && exit\n" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]




