#!/usr/bin/env bash
# share.sh - Send clipboard content via KDE Connect automatically

set -euo pipefail

# create tmp directory
mkdir -p /tmp/kdeconnect-share
TMPDIR=/tmp/kdeconnect-share/

# Get the first connected device
#device=$(kdeconnect-cli -a --id-only | head -n 1)
device="5b47f0807d004996846d0673442f64b2"
device_name=$(kdeconnect-cli -a --name-only | head -n 1)

# check if device is available
if [[ -z "$device" ]]; then
    echo "❌ No device found. Make sure KDE Connect is running and paired."
    exit 1
fi

# Get clipboard content (supports X11 and Wayland)
if command -v wl-paste &>/dev/null; then
    target=$(wl-paste)
elif command -v xclip &>/dev/null; then
    target=$(xclip -o -selection clipboard)
elif command -v xsel &>/dev/null; then
    target=$(xsel --clipboard --output)
else
    echo "❌ No clipboard utility found (install wl-clipboard, xclip, or xsel)."
    exit 1
fi

# check if clibpoard is empty
if [[ -z "$target" ]]; then
    echo "❌ Clipboard is empty."
    exit 1
fi

if wl-paste --type image/png > $TMPDIR/clipboard.png; then
    echo "clipboard mime-type: binary"
    #notify-send -t 3000 " Sending clipboard file to $device_name..."
    file="$TMPDIR/clipboard.png"
    echo file
else
    echo "Clipboard mime-type: text "
    file=$target
fi


# Share clipboard content
if kdeconnect-cli -d "$device" --share "$file"; then
    #echo "✅ Shared clipboard content with $device."
    notify-send -t 4000 "✅ 󰒗   Shared clipboard content with $device_name."
else
    echo "❌ Sharing clipboard has failed"
fi

#rm -r $TMPDIR



