#!/bin/bash

DEVICE="84:AC:60:C6:E7:A1"
NAME="QCY-H3 Lite"

notify-send -t 1000 "Bluetooth" "🔄 Tentando desconectar do $NAME..."

# Envia comando de desconexão
bluetoothctl <<< "disconnect $DEVICE" > /dev/null
