# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk" 
# frontend = "gtk"

# define a client on the right side with host name "iridium"
[right]
hostname = "192.168.1.150"
activate_on_startup = true
# optional list of (known) ip addresses
#ips = ["192.168.0.50"]

### NOTEBOOK
# [left]
# hostname = "192.168.1.160"
# activate_on_startup = true
# port = 4242
# ips = ["192.168.178.189", "192.168.178.172"]
