---
- name: Ensure cargo is installed
  become: true
  ansible.builtin.package:
    name: cargo
    state: present

- name: Install cargo packages
  community.general.cargo:
    name: "{{ item }}"
    state: present
  loop: "{{ cargo_packages | default([]) }}"
