- name: Ensure SSH key exists
  ansible.builtin.openssh_keypair:
    path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    type: ed25519
    state: present
  become: false

- name: Start and enable sshd service
  become: true
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started

- name: Allow SSH through the firewall
  become: true
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true

- name: Reload firewalld
  become: true
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
