#!/bin/bash

DEVICE="B2:91:67:0F:F2:89"
NAME="BLS-B21"
SINK_NAME="bluez_output.B2_91_67_0F_F2_89.1"

notify-send -t 4000 "Bluetooth" "🔄 Tentando conectar ao $NAME..."

# Captura a saída da tentativa de conexão
OUTPUT=$(bluetoothctl <<< "connect $DEVICE")

sleep 3

pactl set-default-sink "$SINK_NAME"
notify-send -t 4000 "Bluetooth" "✅ $NAME conectado e setado como saída padrão!"



