---
- name: Ensure flatpak is installed
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add Flathub remote if not present
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  become: true
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flatpak_apps | default([]) }}"
